CREATE TABLE PRODUCT
(
	BAR_CODE NUMBER(19) auto_increment NOT NULL,
	PRODUCT_DESCRIPTION VARCHAR2(50) NOT NULL
);
CREATE TABLE PRODUCT_PRICE
(
	BAR_CODE NUMBER(19) NOT NULL,
	STORE VARCHAR2(50) NOT NULL,
	PRICE NUMBER(10,2) NOT NULL
);

